{{- if .Values.enableBackendConfig -}}
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  namespace: {{ .Release.Namespace }}
{{ if .Values.backendConfig.name }}
  name: {{ .Values.backendConfig.name }}
{{ else }}
  name: {{ .Chart.Name }}
{{ end }}
spec:
{{- if .Values.backendConfig.securityPolicy }}
  securityPolicy:
    name: {{ .Values.backendConfig.securityPolicy }}
  {{- end }}
{{- end -}}