dependencies:
- name: zookeeper
  version: 2.1.1
  repository: https://kubernetes-charts-incubator.storage.googleapis.com/
  condition: deployments.zookeeper
- name: mysql
  version: 1.5.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: deployments.mysql
- name: minio
  version: 5.0.16
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: deployments.minio
